// mksyscall_windows.pl pc.go
// MACHINE GENERATED BY THE COMMAND ABOVE; DO NOT EDIT

package pc

import "unsafe"
import "syscall"

var (
	modpdh = syscall.NewLazyDLL("pdh.dll")

	procPdhOpenQueryW                = modpdh.NewProc("PdhOpenQueryW")
	procPdhCloseQuery                = modpdh.NewProc("PdhCloseQuery")
	procPdhCollectQueryData          = modpdh.NewProc("PdhCollectQueryData")
	procPdhAddCounterW               = modpdh.NewProc("PdhAddCounterW")
	procPdhRemoveCounter             = modpdh.NewProc("PdhRemoveCounter")
	procPdhGetRawCounterValue        = modpdh.NewProc("PdhGetRawCounterValue")
	procPdhGetFormattedCounterValue  = modpdh.NewProc("PdhGetFormattedCounterValue")
	procPdhGetFormattedCounterArrayW = modpdh.NewProc("PdhGetFormattedCounterArrayW")
)

func PdhOpenQuery(datasrc *uint16, userdata uint32, query *PDH_HQUERY) (pdherr error) {
	r0, _, _ := syscall.Syscall(procPdhOpenQueryW.Addr(), 3, uintptr(unsafe.Pointer(datasrc)), uintptr(userdata), uintptr(unsafe.Pointer(query)))
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhCloseQuery(query PDH_HQUERY) (pdherr error) {
	r0, _, _ := syscall.Syscall(procPdhCloseQuery.Addr(), 1, uintptr(query), 0, 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhCollectQueryData(query PDH_HQUERY) (pdherr error) {
	r0, _, _ := syscall.Syscall(procPdhCollectQueryData.Addr(), 1, uintptr(query), 0, 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhAddCounter(query PDH_HQUERY, fullpath *uint16, userdata uint32, counter *PDH_HCOUNTER) (pdherr error) {
	r0, _, _ := syscall.Syscall6(procPdhAddCounterW.Addr(), 4, uintptr(query), uintptr(unsafe.Pointer(fullpath)), uintptr(userdata), uintptr(unsafe.Pointer(counter)), 0, 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhRemoveCounter(counter PDH_HCOUNTER) (pdherr error) {
	r0, _, _ := syscall.Syscall(procPdhRemoveCounter.Addr(), 1, uintptr(counter), 0, 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhGetRawCounterValue(counter PDH_HCOUNTER, ctype *uint32, value *PDH_RAW_COUNTER) (pdherr error) {
	r0, _, _ := syscall.Syscall(procPdhGetRawCounterValue.Addr(), 3, uintptr(counter), uintptr(unsafe.Pointer(ctype)), uintptr(unsafe.Pointer(value)))
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhGetFormattedCounterValue(counter PDH_HCOUNTER, format uint32, ctype *uint32, value *PDH_FMT_COUNTERVALUE) (pdherr error) {
	r0, _, _ := syscall.Syscall6(procPdhGetFormattedCounterValue.Addr(), 4, uintptr(counter), uintptr(format), uintptr(unsafe.Pointer(ctype)), uintptr(unsafe.Pointer(value)), 0, 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}

func PdhGetFormattedCounterArray(counter PDH_HCOUNTER, format uint32, bufsize *uint32, bufcnt *uint32, item *PDH_FMT_COUNTERVALUE_ITEM) (pdherr error) {
	r0, _, _ := syscall.Syscall6(procPdhGetFormattedCounterArrayW.Addr(), 5, uintptr(counter), uintptr(format), uintptr(unsafe.Pointer(bufsize)), uintptr(unsafe.Pointer(bufcnt)), uintptr(unsafe.Pointer(item)), 0)
	if r0 != 0 {
		pdherr = Errno(r0)
	}
	return
}
